### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Abdullah-Haque** [sanjib-sen/buX_Calendar#4]
![image](https://user-images.githubusercontent.com/66621223/127279103-60a95b04-55f3-4c35-bd4f-db28f6c914ff.png)
Gives this error on login...

`Traceback (most recent call last):
  File "C:\Users\Sanjib Kumar Sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Sanjib Kumar Sen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 33, in run
  File "bux_calendar.py", line 468, in <module>
  File "bux_calendar.py", line 420, in dashboard
  File "bux_calendar.py", line 365, in session
IndexError: list index out of range`

**Comment by sanjib-sen** [comment]
https://github.com/sanjib-sen/Project-bux-Reborn


Used this instead. It is made with JavaScript. Have a better UI and functionality. Just go to the Usage section for the instructions. Let me know if you face any problems.
